const router = require('express').Router();
const authenticate = require('../middlewares/authenticate');
const requirePermission = require('../middlewares/requirePermission');
const requireTicketAccess = require('../middlewares/requireTicketAccess');
const upload = require('../middlewares/upload');
const { list, getMessages, assign, resolve, update, sendMessage, sendMediaMessage, reopen, summarize, deleteMessage, linkContact, forwardMessage, createNote } = require('../controllers/ticketController');
const { updatePreferences } = require('../controllers/ticketPreferencesController');
router.use(authenticate, requirePermission('inbox.view'));
router.get('/', list);
router.post('/', requirePermission('inbox.reopen'), reopen);
router.get('/:id/messages', requireTicketAccess, getMessages);
router.patch('/:id/preferences', requireTicketAccess, updatePreferences);
router.patch('/:id', requireTicketAccess, update);
router.patch('/:id/assign', requireTicketAccess, requirePermission('inbox.assign', 'inbox.transfer'), assign);
router.patch('/:id/resolve', requireTicketAccess, requirePermission('inbox.resolve'), resolve);
router.patch('/:id/link-contact', requireTicketAccess, linkContact);
router.post('/:id/messages', requireTicketAccess, sendMessage);
router.post('/:id/media', requireTicketAccess, upload.single('file'), sendMediaMessage);
router.post('/:id/summarize', requireTicketAccess, summarize);
router.post('/reopen', requirePermission('inbox.reopen'), reopen);
router.delete('/:id/messages/:messageId', requireTicketAccess, requirePermission('inbox.delete_message'), deleteMessage);
router.post('/:id/forward', requireTicketAccess, forwardMessage);
router.post('/:id/notes', requireTicketAccess, createNote);

module.exports = router;
