const router = require('express').Router();
const authenticate = require('../middlewares/authenticate');
const upload = require('../middlewares/upload');
const { list, getMessages, assign, resolve, update, sendMessage, sendMediaMessage, reopen, summarize, deleteMessage, linkContact, forwardMessage, createNote } = require('../controllers/ticketController');
router.use(authenticate);
router.get('/', list);
router.post('/', reopen);
router.get('/:id/messages', getMessages);
router.patch('/:id', update);
router.patch('/:id/assign', assign);
router.patch('/:id/resolve', resolve);
router.patch('/:id/link-contact', linkContact);
router.post('/:id/messages', sendMessage);
router.post('/:id/media', upload.single('file'), sendMediaMessage);
router.post('/:id/summarize', summarize);
router.post('/reopen', reopen);
router.delete('/:id/messages/:messageId', deleteMessage);
router.post('/:id/forward', forwardMessage);
router.post('/:id/notes', createNote);

module.exports = router;
